baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[params]
  # 作者信息配置
  [params.author]
    avatar = "images/test.png"
    intro = "你的名字"
    description = "这是我的博客简介"

[menu]

  [[menu.main]]
    name = "主页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3